[[pages]]
path = "spiral_one.py"
name = "CS-110 Missile Defense (250 Points)"
icon = "â˜„ï¸"

[[pages]]
name = "Spiral 1"
icon = "ğŸš€"
is_section = true

[[pages]]
name = "Spiral 2"
icon = "ğŸ‘©â€ğŸš€"
is_section = true

[[pages]]
name = "Spiral 3"
icon = "ğŸŒ "
is_section = true